### PR TITLE
Updated ToS for 2.5 launch. (bug 1217680)

### PR DESCRIPTION
**Pull request by ddurst**

### CODE REVIEW

**Comment by chuckharmston** [comment]
This completely empties out all the devagreement files. That can't possibly be right?

**Comment by chuckharmston** [comment]
Yeah, something is amiss:

screen shot 2015-10-30 at 1 12 21 pm

**Comment by chuckharmston** [comment]
Baby's first r-

**Comment by ddurst** [comment]
Definitely not baby's first.

**Comment by ddurst** [comment]
Egad.

**Pull request closed without merging**
