### PR TITLE
Try to take advantage of pip 7.0 wheel caching feature

### PR DESCRIPTION
**Pull request by diox**
see https://mail.python.org/pipermail/distutils-sig/2015-May/026474.html

### CODE REVIEW

**Comment by diox** [comment]
Currently failing because of m2crypto compilation, but first run took 7 min 17 sec.

**Comment by diox** [comment]
Going to let the last rebuild finish but the install step went from 300-400 seconds to 60-70. Success!

**Comment by eviljeff** [comment]
:speedboat: r+

**Comment by robhudson** [comment]
Well done.

**Pull request merged**
