### PR TITLE
Remove Tarako checkbox and subscription model Bug 741679 and bug 1059385

### PR DESCRIPTION
**Pull request by eviljeff**

### CODE REVIEW

**Comment by diox** [comment]
Is there any reason to have those 2 bugs in a single PR, and if not, can you split that ? Easier if we need to revert one of the bugs later.

**Comment by eviljeff** [comment]
no reason really... I was working on something else that touched the same few lines and remembered about these bugs.

**Comment by eviljeff** [comment]
Alright, changed this pull to be just bug 741679.

**Comment by eviljeff** [comment]
Added a commit for the 2nd bug.  Both commits are independent of either other; they just touch adjacent lines of code.

**Comment by diox** [comment]
r+

**Pull request merged**
