### PR TITLE
Update add-ons permission checks to use ContentTools:AddonSubmit.

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @washort @ngokevin 

Separately, mat and I created groups and permissions for extension review. This replaces all instances of `Extensions:Review` with `ContentTools:AddonReview`.

### CODE REVIEW

**Comment by chuckharmston** [comment]
I did not mean to merge this, and am not quite sure how it happened.

**Comment by chuckharmston** [comment]
Oh, ha. I didn't merge it, I went to amend the commit and forgot to recommit it after changes. Whoops.

**Comment by chuckharmston** [comment]
Build errors here are unrelated: https://travis-ci.org/mozilla/zamboni/builds/84414106

Will close/reopen to kick off another build.

**Comment by eviljeff** [comment]
is it too late to say `Extensions:Review` kinda makes more sense?  The permission is to use the API, rather than the tool, right?

**Comment by chuckharmston** [comment]
@eviljeff It's probably not too late, but I'm trying to take the path of least resistance to unblock FxOS QA. The group we already use is ContentTools:AddonReview, so I went with that to avoid having to write a brittle migration.

**Comment by ngokevin** [comment]
r+

**Pull request merged**
