### PR TITLE
Bug 990000 - input notification image aligned

### PR DESCRIPTION
**Pull request by shiveeg1**
Team member email input notification image is aligned correctly.

### CODE REVIEW

**Comment by eviljeff** [comment]
These numbers don't align the icon correctly (I played around with Inspect Element and changed the css).  Its the vertical number which is causing the icon to be clipped by the bottom of the field.
r-

**Comment by shiveeg1** [comment]
Thanks for the explanation eviljeff. So do need only the vertical spacing or the horizontal too to align the notification next to the border of the field ?

**Comment by eviljeff** [comment]
To be perfect you need both - so the numbers in your original patch fix the horizontal issue so the icon is closer to the border; but you need some vertical adjustment to stop the icons being clipped by the bottom border.

**Comment by shiveeg1** [comment]
Got it! made the vertical and horizontal changes and squashed both commits into one. Hope this one works . Thanks eviljeff !

**Comment by eviljeff** [comment]
r+

**Pull request merged**
