### PR TITLE
Update (almost) all requirements

### PR DESCRIPTION
**Pull request by diox**
Who knows, it might even work !

### CODE REVIEW

**Comment by washort** [comment]
nice, you got further than i did :) r+

**Comment by diox** [comment]
@jasonthomas could you please build wheels for the compiled packages and put them in pyrepo/zamboni ? Not all those deps publish wheels, and I fear the ones I'd build on my machine would not be compatible (wrong glibc)

**Comment by jasonthomas** [comment]
I've built the wheels including cryptography and placed them in pyrepo/zamboni

**Comment by diox** [comment]
Alright thanks ! I've copied the rest, hopefully I haven't forgotten anything, let's merge !

**Pull request merged**
