### PR TITLE
Display GUID in developper pages (bug 1119851)

### PR DESCRIPTION
**Pull request by diox**
https://bugzilla.mozilla.org/show_bug.cgi?id=1119851

### CODE REVIEW

**Comment by diox** [comment]
Waiting on answers to https://bugzilla.mozilla.org/show_bug.cgi?id=1119851#c1

**Comment by diox** [comment]
@clouserw r?

**Comment by diox** [comment]
screen shot 2015-01-06 at 19 12 54
screen shot 2015-01-06 at 19 12 50

**Comment by clouserw** [comment]
r+ thanks

**Pull request merged**
