### PR TITLE
Update prod requirements to include compiled.txt.

### PR DESCRIPTION
**Pull request by jasonthomas**
Related to Bug 1156442.

r? @robhudson

### CODE REVIEW

**Comment by diox** [comment]
So the goal is to stop using RPMs and simply have wheels for every compiled dependency ?

**Comment by robhudson** [comment]
Just to understand completely... we still need ops to create the wheels for the platform but when finished you put them on pyrepo and they get pip installed like the rest of the packages. Is that correct?

**Comment by jasonthomas** [comment]
> So the goal is to stop using RPMs and simply have wheels for every compiled dependency ?
Yes. I think it would be easier to maintain project specific dependencies going forward.

> Just to understand completely...  we still need ops to create the wheels for the platform but when finished you put them on pyrepo
Anyone should be able to generate the wheel packages within a RHEL6 env, but ops can continue to build them as needed.

> and they get pip installed like the rest of the packages. Is that correct?
Correct.

**Comment by diox** [comment]
cool, thanks!

**Comment by robhudson** [comment]
Yeah, I like this. Thanks @jasonthomas.  r+

**Pull request merged**
