### PR TITLE
remove Tarako reviewer queue - bug 1223401

### PR DESCRIPTION
**Pull request by eviljeff**
Not going to merge this yet, but getting it ready to go.

### CODE REVIEW

**Comment by ngokevin** [comment]
ready?

**Comment by eviljeff** [comment]
Might be a few weeks before I'd merge it, but its ready for review any time.

**Comment by diox** [comment]
lgtm

**Comment by diox** [comment]
Finally had the time to test it locally, didn't find any issues. r+

**Comment by ddurst** [comment]
So... r+ but needs conflicts resolved?

**Comment by eviljeff** [comment]
It's not ready to merge yet - we have to clear the queue first and our contractors have gone awol. :sob:

**Comment by ddurst** [comment]
(they still awol, @eviljeff ?)

**Comment by eviljeff** [comment]
they are still awol but a few volunteers have cleared most - there are only 3 left, which I'd do myself if I had the device with me.  So it might have to wait a few more weeks.

**Comment by eviljeff** [comment]
remaining submissions cleared, rebase, and tarako be gone!
(front end support remains)

**Pull request merged**
