### PR TITLE
Wrong information on App reviewers Portal (bug 1168477)

### PR DESCRIPTION
**Pull request by viswaprasath**
Changed "was viewing this add-on first." to "was viewing this app first."

### CODE REVIEW

**Comment by eviljeff** [comment]
can you change the commit summary to explain what is being changed?  Ideally include the bug # in there too.  Same with the pull request summary,

**Comment by viswaprasath** [comment]
**Bug:** https://bugzilla.mozilla.org/show_bug.cgi?id=1168477

**Changes Info**
*In Line number 241*

format(gettext('{name} was viewing this **add-on** first.') is changed to format(gettext('{name} was viewing this **app** first.')

The packaged zip(html,css,js,manifest) in Firefox Marketplace are generally called as Apps, and we don't use the name add-on in Firefox Marketplace.

**Comment by eviljeff** [comment]
@viswaprasath are you going to be able to make the changes to the commit & pull title?

**Comment by eviljeff** [comment]
thanks!

**Pull request merged**
