### PR TITLE
Bump elasticsearch + elasticsearch-dsl (bug 846349)

### PR DESCRIPTION
**Pull request by diox**

### CODE REVIEW

**Comment by diox** [comment]
Welp, guess we'll need to make some adjustments to our code before upgrading those...

**Comment by ngokevin** [comment]
rob bumped ES, so bumping DSL should be trivial now

**Comment by diox** [comment]
Rebased, we'll see.

**Comment by diox** [comment]
Fail :(

**Comment by ngokevin** [comment]
is this PR rebased?

**Comment by ngokevin** [comment]
Closing for now.

**Pull request closed without merging**
