### PR TITLE
Remove unused ActivityLogAttachments (bug 1198817)

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by diox** [comment]
Less code, yay !

**Comment by robhudson** [comment]
Tests pass, :shipit:?

BTW, do we rename our migration files or keep the auto generated name?

**Comment by robhudson** [comment]
@ngokevin Mind taking a quick look?

**Comment by ngokevin** [comment]
r+ we're not showing activitylogattachments in the reviewer logs so this seems okay.

**Pull request merged**
