### PR TITLE
Respect existing data for load_prices command

### PR DESCRIPTION
**Pull request by kumar303**
@andymckay r?

### CODE REVIEW

**Comment by andymckay** [comment]
r+ with the comments in IRC that we should drop this command and stop supporting it, since Docker loads init data which sets it up correctly and @washort has a FakeData framework. This command made sense once, don't think it does any more.

**Comment by kumar303** [comment]
in the case where Docker doesn't work (now or in the future) it's nice to have an option to run things manually though

**Comment by andymckay** [comment]
I don't think have Docker not working is going to be an option when we start deploying to prod using Docker :)

**Comment by washort** [comment]
I expect that whatever fake-data scripting we do will probably just call this code or something very like it.

**Pull request merged**
