### PR TITLE
Remove obsolete images (bug 1221717)

### PR DESCRIPTION
**Pull request by diox**
I tried to avoid touching css files for now, just removing what is clearly not used anywhere, but I did modify a couple css files where it was obviously not used.

### CODE REVIEW

**Comment by spasovski** [comment]
Epic PR is epic!

**Comment by diox** [comment]
I might have to split this up... Didn't expect github to choke on it.

**Comment by diox** [comment]
Did some browsing around locally and could not find any issues.

**Comment by ngokevin** [comment]
r+

**Pull request merged**
