### PR TITLE
Remove dependency on SQLAlchemy (bug 1159220)

### PR DESCRIPTION
**Pull request by diox**
https://bugzilla.mozilla.org/show_bug.cgi?id=1159220

Also stop having a `SERVICES_DATABASE` setting, since it actually points to the default database anyway (discussed with @jasonthomas)

### CODE REVIEW

**Comment by robhudson** [comment]
Shouldn't that also be converted to a regular django view with a url instead of the python/wsgi thing it is now? Or is that a later bug?

**Comment by robhudson** [comment]
r+. This looks fine but I'd be interested to see it moved into a regular django app if possible.

**Comment by diox** [comment]
See discussion in the bug. It should, but it's more work, so I've created a follow-up bug to take care of that later: https://bugzilla.mozilla.org/show_bug.cgi?id=1159746

**Comment by robhudson** [comment]
Ok, r+ then.

**Pull request merged**
