### PR TITLE
Bump Elasticsearch libs (bug 846349)

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by diox** [comment]
FAILED (errors=33)

r- then :)

**Comment by robhudson** [comment]
Looks like mostly in the feed, hmm. I tested `mkt.search` locally but not feed. I'll look closer.

**Comment by diox** [comment]
So, I reproduced the failures locally... but not once I merged #2943 (which updates DRF) into this branch.

**Comment by robhudson** [comment]
Oh hey, I rebased and all tests pass except for this weird langpack etag one. @diox does that look odd to you?

**Comment by diox** [comment]
Yeah it's failing for everyone, not just you. Looking into it.

**Comment by diox** [comment]
This is fixed on master.

**Comment by robhudson** [comment]
Thanks for the update. Rebased and force pushed.

**Comment by robhudson** [comment]
Woo! Tests pass!

**Comment by diox** [comment]
r+ let's try it

**Comment by robhudson** [comment]
Merged: https://github.com/mozilla/zamboni/commit/29f36da

**Pull request closed without merging**
