### PR TITLE
Revert use table cleanup (bug 1131717)

### PR DESCRIPTION
**Pull request by kumar303**
This migration is too slow for prod right now

WIP, DO NOT MERGE

### CODE REVIEW

**Comment by clouserw** [comment]
Thanks for space change.  The revert part (the new .sql file) shouldn't be a part of this patch.  That's just something jason runs on stage manually - that way it won't mess anyone else up and when we test the real fix later it will work as expected on stage.

**Comment by kumar303** [comment]
Well, we need a way to see what code will break too when the database migration is not run so this patch will run the suite hopefully in a manner similar to prod (in the case where the removal migration is disabled)

**Comment by clouserw** [comment]
r+

**Comment by kumar303** [comment]
This was not merged to master because it will break local installs for each developer. Instead I pushed it to this branch: https://github.com/mozilla/zamboni/compare/master...revert-1131717 It has also been cherry picked into the release tag: https://github.com/mozilla/zamboni/compare/2015.02.24...2015.03.03

**Comment by kumar303** [comment]
The user table cleanup will be reintroduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1139188

**Pull request closed without merging**
