### PR TITLE
Add new languages: sw, wo, ff, ar. Bug 1151944

### PR DESCRIPTION
**Pull request by clouserw**

### CODE REVIEW

**Comment by clouserw** [comment]
Marked as not ready, waiting on L10n to catch up

**Comment by andymckay** [comment]
Do other repos like webpay, marketplace-stats, fireplace etc need these?

**Comment by clouserw** [comment]
fireplace reads it from zamboni (as a data attribute).  I kind of think (hope?) the others do too :)

**Comment by clouserw** [comment]
we're doing these one at a time, so closing this

**Pull request closed without merging**
